name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_anilist: yes
          plugin_anilist_medias: anime, manga            # Display both animes and mangas
          plugin_anilist_sections: favorites, characters # Display only favorites and characters sections
          plugin_anilist_limit: 2                        # Limit to 2 entry per section (characters section excluded)
          plugin_anilist_limit_characters: 22            # Limit to 22 characters in characters section
          plugin_anilist_shuffle: yes                    # Shuffle data for more varied outputs
          plugin_anilist_user: .user.login               # Use same username as GitHub login

